export type StateInfo = {
  name: string;
  cities: string[];
  colTier: "very_high" | "high" | "moderate" | "affordable";
  monthlyRent: string;
  climate: string;
  publicTransport: "excellent" | "good" | "limited" | "poor";
  intlTip: string;
  places: string[];
};

export const STATE_DATA: Record<string, StateInfo> = {
  AL: { name: "Alabama", cities: ["Birmingham", "Huntsville", "Tuscaloosa"], colTier: "affordable", monthlyRent: "$800–$1,100", climate: "Subtropical — hot summers, mild winters", publicTransport: "poor", intlTip: "Low cost of living; campus life is central since public transit is limited.", places: ["Birmingham Civil Rights Institute", "U.S. Space & Rocket Center", "Gulf Shores beaches", "Cheaha State Park"] },
  AZ: { name: "Arizona", cities: ["Phoenix", "Tempe", "Tucson"], colTier: "moderate", monthlyRent: "$1,200–$1,800", climate: "Desert — very hot summers, mild winters", publicTransport: "limited", intlTip: "Heat can be extreme in summer; the dry climate is very different from most of Asia and Europe.", places: ["Grand Canyon National Park", "Sedona Red Rock Country", "Monument Valley", "Antelope Canyon"] },
  AR: { name: "Arkansas", cities: ["Fayetteville", "Little Rock", "Jonesboro"], colTier: "affordable", monthlyRent: "$700–$1,000", climate: "Humid subtropical — hot summers, cold winters", publicTransport: "poor", intlTip: "Very affordable; car ownership is almost essential outside of campus.", places: ["Ozark Mountains", "Hot Springs National Park", "Buffalo National River", "Thorncrown Chapel"] },
  CA: { name: "California", cities: ["Los Angeles", "San Francisco", "San Diego", "Berkeley"], colTier: "very_high", monthlyRent: "$2,200–$3,500", climate: "Mediterranean to semi-arid — warm dry summers, mild winters", publicTransport: "good", intlTip: "Largest international student population in the US. Very high rent — on-campus housing is often cheaper.", places: ["Yosemite National Park", "Golden Gate Bridge", "Big Sur coastline", "Joshua Tree National Park", "Napa Valley"] },
  CO: { name: "Colorado", cities: ["Denver", "Boulder", "Fort Collins", "Colorado Springs"], colTier: "high", monthlyRent: "$1,500–$2,200", climate: "Semi-arid — sunny, cold winters with significant snow", publicTransport: "limited", intlTip: "Popular outdoor lifestyle; housing near Denver has risen sharply. Great skiing in winter.", places: ["Rocky Mountain National Park", "Mesa Verde", "Red Rocks Amphitheatre", "Maroon Bells", "Garden of the Gods"] },
  CT: { name: "Connecticut", cities: ["New Haven", "Hartford", "Storrs", "Stamford"], colTier: "high", monthlyRent: "$1,600–$2,400", climate: "Humid continental — cold winters, warm humid summers", publicTransport: "good", intlTip: "Close to NYC via Metro-North train (45–90 min). Strong Ivy League and liberal arts presence.", places: ["Yale University campus", "Mystic Seaport Museum", "Mark Twain House", "Sleeping Giant State Park"] },
  DE: { name: "Delaware", cities: ["Wilmington", "Newark", "Dover"], colTier: "moderate", monthlyRent: "$1,200–$1,600", climate: "Humid subtropical — moderate, four distinct seasons", publicTransport: "limited", intlTip: "No state sales tax; close to Philadelphia and Washington D.C.", places: ["Rehoboth Beach", "First State National Monument", "Brandywine Valley", "Cape Henlopen State Park"] },
  DC: { name: "Washington D.C.", cities: ["Washington"], colTier: "very_high", monthlyRent: "$2,500–$3,800", climate: "Humid subtropical — hot summers, cold winters", publicTransport: "excellent", intlTip: "Best public transit on the east coast (Metro). High rent but world-class policy and networking opportunities.", places: ["National Mall & Monuments", "Smithsonian museums", "Georgetown waterfront", "U.S. Capitol"] },
  FL: { name: "Florida", cities: ["Miami", "Orlando", "Tampa", "Gainesville", "Tallahassee"], colTier: "moderate", monthlyRent: "$1,400–$2,200", climate: "Tropical — hot, humid, hurricane season June–November", publicTransport: "limited", intlTip: "No state income tax. Miami has one of the largest international communities in the US. Budget for hurricane insurance.", places: ["Everglades National Park", "Kennedy Space Center", "St. Augustine Old Town", "Florida Keys", "Clearwater Beach"] },
  GA: { name: "Georgia", cities: ["Atlanta", "Athens", "Savannah", "Augusta"], colTier: "moderate", monthlyRent: "$1,200–$1,900", climate: "Humid subtropical — hot summers, mild winters", publicTransport: "limited", intlTip: "Atlanta is a major international hub with MARTA rail. Fast-growing tech and film industries.", places: ["Savannah Historic District", "Atlanta BeltLine", "Stone Mountain", "Georgia Aquarium", "Cumberland Island"] },
  HI: { name: "Hawaii", cities: ["Honolulu", "Hilo", "Kailua"], colTier: "very_high", monthlyRent: "$2,000–$3,000", climate: "Tropical — warm year-round, trade winds, occasional heavy rain", publicTransport: "limited", intlTip: "Beautiful but expensive. Groceries cost roughly 30% more than the mainland due to shipping costs.", places: ["Waikiki Beach", "Volcanoes National Park", "Na Pali Coast", "Pearl Harbor", "Haleakalā National Park"] },
  ID: { name: "Idaho", cities: ["Boise", "Moscow", "Pocatello", "Twin Falls"], colTier: "affordable", monthlyRent: "$900–$1,300", climate: "Semi-arid — cold winters, warm summers", publicTransport: "poor", intlTip: "Growing tech scene in Boise; very affordable compared to the west coast. Car is essential.", places: ["Craters of the Moon", "Sawtooth Mountains", "Sun Valley", "Shoshone Falls", "Coeur d'Alene Lake"] },
  IL: { name: "Illinois", cities: ["Chicago", "Champaign-Urbana", "Evanston", "Peoria"], colTier: "moderate", monthlyRent: "$1,100–$2,000", climate: "Humid continental — very cold winters, hot humid summers", publicTransport: "excellent", intlTip: "Chicago's El train is excellent for city navigation. Campus towns like Champaign are much cheaper than the city.", places: ["Millennium Park Chicago", "Navy Pier", "Starved Rock State Park", "Art Institute of Chicago"] },
  IN: { name: "Indiana", cities: ["Indianapolis", "Bloomington", "West Lafayette", "South Bend"], colTier: "affordable", monthlyRent: "$800–$1,200", climate: "Humid continental — cold winters, warm summers", publicTransport: "poor", intlTip: "Very affordable; strong engineering programs at Purdue. Car required outside Indianapolis.", places: ["Indiana Dunes National Park", "Brown County State Park", "Indianapolis Motor Speedway", "Turkey Run State Park"] },
  IA: { name: "Iowa", cities: ["Iowa City", "Ames", "Des Moines", "Cedar Falls"], colTier: "affordable", monthlyRent: "$750–$1,100", climate: "Humid continental — very cold winters, hot summers", publicTransport: "poor", intlTip: "Extremely affordable with strong research programs. Winters are very cold — invest in proper clothing early.", places: ["Effigy Mounds National Monument", "Pikes Peak State Park", "Iowa Great Lakes", "Field of Dreams movie site"] },
  KS: { name: "Kansas", cities: ["Lawrence", "Manhattan", "Wichita", "Topeka"], colTier: "affordable", monthlyRent: "$750–$1,100", climate: "Humid continental — hot summers, cold winters, tornado risk", publicTransport: "poor", intlTip: "Low cost of living; car is essential. Be prepared for tornado season April–June.", places: ["Tallgrass Prairie National Preserve", "Flint Hills Scenic Byway", "Monument Rocks", "Eisenhower Presidential Library"] },
  KY: { name: "Kentucky", cities: ["Lexington", "Louisville", "Bowling Green"], colTier: "affordable", monthlyRent: "$800–$1,200", climate: "Humid subtropical — four distinct seasons, hot summers", publicTransport: "poor", intlTip: "Very low cost of living; welcoming university towns with strong community feel.", places: ["Mammoth Cave National Park", "Red River Gorge", "Louisville Bourbon Trail", "Daniel Boone National Forest"] },
  LA: { name: "Louisiana", cities: ["New Orleans", "Baton Rouge", "Lafayette"], colTier: "affordable", monthlyRent: "$900–$1,400", climate: "Subtropical — hot, humid, hurricane season June–November", publicTransport: "limited", intlTip: "Vibrant culture and food scene. Budget for hurricane season preparedness; flood insurance matters.", places: ["New Orleans French Quarter", "Bayou swamp tours", "Oak Alley Plantation", "Atchafalaya Basin"] },
  ME: { name: "Maine", cities: ["Portland", "Orono", "Augusta"], colTier: "moderate", monthlyRent: "$1,000–$1,500", climate: "Humid continental — very cold snowy winters, mild summers", publicTransport: "poor", intlTip: "Small, tight-knit communities. Beautiful but harsh winters — waterproof boots and heavy coats are essential.", places: ["Acadia National Park", "Portland Head Light", "Kennebunkport", "Baxter State Park"] },
  MD: { name: "Maryland", cities: ["College Park", "Baltimore", "Bethesda", "Annapolis"], colTier: "high", monthlyRent: "$1,500–$2,400", climate: "Humid subtropical — hot summers, cold winters", publicTransport: "good", intlTip: "Close to DC; MARC train and Metro accessible. Costs are high near DC suburbs but more affordable further inland.", places: ["Assateague Island", "Chesapeake Bay", "Ocean City boardwalk", "Antietam Battlefield"] },
  MA: { name: "Massachusetts", cities: ["Boston", "Cambridge", "Worcester", "Amherst"], colTier: "very_high", monthlyRent: "$2,000–$3,200", climate: "Humid continental — cold winters, warm humid summers", publicTransport: "excellent", intlTip: "MBTA connects most Boston-area schools. Huge international community around Cambridge/Boston. Apply for housing early.", places: ["Freedom Trail Boston", "Cape Cod National Seashore", "Martha's Vineyard", "Salem Historic District"] },
  MI: { name: "Michigan", cities: ["Ann Arbor", "East Lansing", "Detroit", "Kalamazoo"], colTier: "moderate", monthlyRent: "$1,000–$1,500", climate: "Humid continental — very cold snowy winters, warm summers", publicTransport: "limited", intlTip: "Ann Arbor is expensive; other campus towns are affordable. Budget for heating and winter clothing.", places: ["Pictured Rocks National Lakeshore", "Mackinac Island", "Sleeping Bear Dunes", "Tahquamenon Falls"] },
  MN: { name: "Minnesota", cities: ["Minneapolis", "Saint Paul", "Duluth", "Rochester"], colTier: "moderate", monthlyRent: "$1,000–$1,600", climate: "Humid continental — extremely cold winters, warm summers", publicTransport: "good", intlTip: "Some of the coldest winters in the lower 48 states. Minneapolis–Saint Paul has a solid light rail network.", places: ["Boundary Waters Canoe Area", "Minnehaha Falls", "Voyageurs National Park", "Mall of America"] },
  MS: { name: "Mississippi", cities: ["Oxford", "Jackson", "Starkville", "Hattiesburg"], colTier: "affordable", monthlyRent: "$650–$950", climate: "Humid subtropical — very hot summers, mild winters", publicTransport: "poor", intlTip: "One of the lowest costs of living in the US. Car is essential everywhere.", places: ["Natchez Trace Parkway", "Gulf Islands National Seashore", "Mississippi Blues Trail", "Vicksburg National Battlefield"] },
  MO: { name: "Missouri", cities: ["St. Louis", "Columbia", "Kansas City", "Springfield"], colTier: "affordable", monthlyRent: "$850–$1,300", climate: "Humid continental — hot summers, cold winters", publicTransport: "limited", intlTip: "Very affordable; strong research universities. Gateway to both coasts with major airport hubs.", places: ["Gateway Arch St. Louis", "Ozark National Scenic Riverways", "Silver Dollar City", "Mark Twain's Hannibal"] },
  MT: { name: "Montana", cities: ["Missoula", "Bozeman", "Billings", "Great Falls"], colTier: "moderate", monthlyRent: "$1,000–$1,500", climate: "Semi-arid continental — very cold winters, warm summers", publicTransport: "poor", intlTip: "Beautiful outdoors; Bozeman costs rising fast due to growth. Car is essential everywhere.", places: ["Glacier National Park", "Yellowstone north entrance", "Beartooth Highway", "Going-to-the-Sun Road"] },
  NE: { name: "Nebraska", cities: ["Lincoln", "Omaha", "Kearney"], colTier: "affordable", monthlyRent: "$800–$1,200", climate: "Humid continental — cold winters, hot summers", publicTransport: "poor", intlTip: "Very affordable; friendly university towns. Growing tech corridor in Omaha.", places: ["Chimney Rock", "Scotts Bluff National Monument", "Sandhills Prairie", "Fontenelle Forest Omaha"] },
  NV: { name: "Nevada", cities: ["Las Vegas", "Reno", "Henderson"], colTier: "moderate", monthlyRent: "$1,200–$1,700", climate: "Desert — very hot dry summers, mild winters", publicTransport: "limited", intlTip: "No state income tax. Las Vegas lifestyle can be very distracting — budget and schedule carefully.", places: ["Red Rock Canyon", "Valley of Fire State Park", "Lake Tahoe south shore", "Great Basin National Park"] },
  NH: { name: "New Hampshire", cities: ["Durham", "Manchester", "Hanover", "Concord"], colTier: "high", monthlyRent: "$1,400–$2,000", climate: "Humid continental — very cold snowy winters, warm summers", publicTransport: "poor", intlTip: "No state income or sales tax. Car essential; Boston accessible by commuter rail from Manchester.", places: ["White Mountain National Forest", "Mount Washington", "Lake Winnipesaukee", "Kancamagus Highway"] },
  NJ: { name: "New Jersey", cities: ["Princeton", "New Brunswick", "Newark", "Hoboken"], colTier: "very_high", monthlyRent: "$1,800–$2,800", climate: "Humid subtropical/continental — four seasons", publicTransport: "excellent", intlTip: "NJ Transit connects to NYC in 30–60 min. High cost of living statewide but excellent job market access.", places: ["Cape May Victorian district", "Liberty State Park", "Delaware Water Gap", "Jersey Shore beaches"] },
  NM: { name: "New Mexico", cities: ["Albuquerque", "Las Cruces", "Santa Fe"], colTier: "affordable", monthlyRent: "$850–$1,300", climate: "Semi-arid — dry, sunny, cold at elevation in winter", publicTransport: "poor", intlTip: "Very affordable with rich cultural diversity. ABQ has a growing STEM and national labs sector.", places: ["White Sands National Park", "Carlsbad Caverns", "Santa Fe Plaza", "Taos Pueblo"] },
  NY: { name: "New York", cities: ["New York City", "Ithaca", "Rochester", "Albany", "Buffalo"], colTier: "very_high", monthlyRent: "$2,500–$4,500", climate: "Humid continental — cold winters, hot summers (NYC milder)", publicTransport: "excellent", intlTip: "NYC has the best transit in the US. Upstate NY is dramatically more affordable. Largest international student population nationwide.", places: ["Niagara Falls", "Adirondack Mountains", "Central Park NYC", "Hudson Valley", "Finger Lakes wine region"] },
  NC: { name: "North Carolina", cities: ["Chapel Hill", "Durham", "Raleigh", "Charlotte", "Greensboro"], colTier: "moderate", monthlyRent: "$1,100–$1,700", climate: "Humid subtropical — hot summers, mild winters", publicTransport: "limited", intlTip: "Research Triangle is a major tech/pharma hub. Fast-growing international community with competitive programs.", places: ["Blue Ridge Parkway", "Great Smoky Mountains", "Outer Banks", "Biltmore Estate Asheville"] },
  ND: { name: "North Dakota", cities: ["Fargo", "Grand Forks", "Bismarck"], colTier: "affordable", monthlyRent: "$750–$1,100", climate: "Humid continental — extremely cold winters, warm summers", publicTransport: "poor", intlTip: "Very affordable; extreme cold is the main challenge. Smaller international student community — expect to stand out.", places: ["Theodore Roosevelt National Park", "Medora Badlands", "International Peace Garden", "Fort Union Trading Post"] },
  OH: { name: "Ohio", cities: ["Columbus", "Cleveland", "Cincinnati", "Athens", "Oxford"], colTier: "affordable", monthlyRent: "$850–$1,400", climate: "Humid continental — cold winters, warm humid summers", publicTransport: "limited", intlTip: "Affordable with strong research universities. Columbus and Cleveland have growing tech and startup scenes.", places: ["Cuyahoga Valley National Park", "Rock & Roll Hall of Fame", "Hocking Hills State Park", "Cedar Point"] },
  OK: { name: "Oklahoma", cities: ["Norman", "Stillwater", "Tulsa", "Oklahoma City"], colTier: "affordable", monthlyRent: "$750–$1,100", climate: "Humid subtropical — hot summers, cold winters, tornado risk", publicTransport: "poor", intlTip: "Very affordable. Be prepared for tornado season. Strong aerospace, energy, and agriculture programs.", places: ["Wichita Mountains Wildlife Refuge", "Chickasaw National Recreation Area", "Route 66 historic sites", "Talimena Scenic Drive"] },
  OR: { name: "Oregon", cities: ["Portland", "Eugene", "Corvallis", "Ashland"], colTier: "high", monthlyRent: "$1,400–$2,100", climate: "Oceanic — mild rainy winters, warm dry summers", publicTransport: "good", intlTip: "No state sales tax. Portland has good transit. Rainy season lasts Oct–May — a significant mental health consideration.", places: ["Crater Lake National Park", "Columbia River Gorge", "Cannon Beach Haystack Rock", "Oregon Coast Highway"] },
  PA: { name: "Pennsylvania", cities: ["Philadelphia", "Pittsburgh", "State College", "Bethlehem"], colTier: "moderate", monthlyRent: "$1,100–$1,900", climate: "Humid continental — cold winters, hot humid summers", publicTransport: "good", intlTip: "SEPTA in Philly and Port Authority in Pittsburgh. Very strong university presence statewide.", places: ["Independence Hall Philadelphia", "Gettysburg Battlefield", "Fallingwater", "Delaware Water Gap"] },
  RI: { name: "Rhode Island", cities: ["Providence", "Newport", "Warwick"], colTier: "high", monthlyRent: "$1,500–$2,200", climate: "Humid continental — cold winters, warm summers", publicTransport: "limited", intlTip: "Smallest state; close to Boston by commuter rail (45 min). RIPTA bus covers Providence well.", places: ["Newport Mansions", "Block Island", "Narragansett Beach", "Roger Williams Park"] },
  SC: { name: "South Carolina", cities: ["Columbia", "Charleston", "Clemson", "Greenville"], colTier: "moderate", monthlyRent: "$1,000–$1,500", climate: "Humid subtropical — hot summers, mild winters", publicTransport: "poor", intlTip: "Growing university towns with affordable coastal living options.", places: ["Charleston Historic District", "Congaree National Park", "Myrtle Beach", "Table Rock State Park"] },
  SD: { name: "South Dakota", cities: ["Vermillion", "Brookings", "Sioux Falls", "Rapid City"], colTier: "affordable", monthlyRent: "$750–$1,100", climate: "Humid continental — cold winters, hot summers", publicTransport: "poor", intlTip: "Very affordable; no state income tax. Small international student community — expect tight-knit connections.", places: ["Mount Rushmore", "Badlands National Park", "Custer State Park", "Wind Cave National Park"] },
  TN: { name: "Tennessee", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga"], colTier: "moderate", monthlyRent: "$1,100–$1,700", climate: "Humid subtropical — hot summers, mild winters", publicTransport: "limited", intlTip: "No state income tax. Nashville costs have risen sharply; campus towns like Knoxville are still affordable.", places: ["Great Smoky Mountains National Park", "Nashville Broadway district", "Dollywood", "Graceland Memphis"] },
  TX: { name: "Texas", cities: ["Austin", "Houston", "Dallas", "College Station", "San Antonio"], colTier: "moderate", monthlyRent: "$1,200–$2,000", climate: "Varies: hot/humid in Houston to semi-arid in West TX", publicTransport: "limited", intlTip: "No state income tax. Large international student communities across the state. Car is highly recommended everywhere.", places: ["Big Bend National Park", "San Antonio River Walk", "Padre Island National Seashore", "Austin 6th Street", "Guadalupe Mountains"] },
  UT: { name: "Utah", cities: ["Salt Lake City", "Provo", "Logan", "Ogden"], colTier: "moderate", monthlyRent: "$1,100–$1,700", climate: "Semi-arid — cold winters, hot dry summers", publicTransport: "good", intlTip: "TRAX light rail in Salt Lake City. Outdoor activities and skiing are a huge part of student culture here.", places: ["Zion National Park", "Bryce Canyon", "Arches National Park", "Canyonlands", "Monument Valley"] },
  VT: { name: "Vermont", cities: ["Burlington", "Middlebury", "Montpelier"], colTier: "moderate", monthlyRent: "$1,100–$1,600", climate: "Humid continental — very cold snowy winters, mild summers", publicTransport: "poor", intlTip: "Small campus communities; beautiful scenery. Car essential outside Burlington.", places: ["Green Mountain National Forest", "Burlington waterfront", "Stowe ski resort", "Vermont Fall Foliage Drive"] },
  VA: { name: "Virginia", cities: ["Charlottesville", "Blacksburg", "Fairfax", "Richmond", "Norfolk"], colTier: "high", monthlyRent: "$1,400–$2,200", climate: "Humid subtropical/continental — four distinct seasons", publicTransport: "good", intlTip: "Northern VA near DC is expensive; UVA (Charlottesville) and Virginia Tech (Blacksburg) are more affordable.", places: ["Shenandoah National Park", "Colonial Williamsburg", "Arlington National Cemetery", "Skyline Drive"] },
  WA: { name: "Washington", cities: ["Seattle", "Pullman", "Bellingham", "Spokane"], colTier: "high", monthlyRent: "$1,600–$2,500", climate: "Oceanic — mild, very rainy winters, warm dry summers", publicTransport: "good", intlTip: "No state income tax. Seattle is expensive; WSU in Pullman is significantly more affordable. Large Asian student community.", places: ["Mount Rainier National Park", "Olympic National Park", "Pike Place Market Seattle", "North Cascades"] },
  WV: { name: "West Virginia", cities: ["Morgantown", "Huntington", "Charleston"], colTier: "affordable", monthlyRent: "$700–$1,000", climate: "Humid continental — cold winters, warm summers", publicTransport: "poor", intlTip: "Very affordable; car is essential. WVU in Morgantown has a growing international community.", places: ["New River Gorge National Park", "Blackwater Falls State Park", "Seneca Rocks", "Harpers Ferry"] },
  WI: { name: "Wisconsin", cities: ["Madison", "Milwaukee", "Green Bay", "Eau Claire"], colTier: "moderate", monthlyRent: "$950–$1,400", climate: "Humid continental — very cold snowy winters, warm summers", publicTransport: "good", intlTip: "Madison has good bus transit. Winters are very cold — budget for higher heating costs.", places: ["Apostle Islands National Lakeshore", "Wisconsin Dells", "Door County Peninsula", "Devil's Lake State Park"] },
  WY: { name: "Wyoming", cities: ["Laramie", "Casper", "Cheyenne"], colTier: "affordable", monthlyRent: "$800–$1,200", climate: "Semi-arid — cold windy winters, warm summers", publicTransport: "poor", intlTip: "Least populous state; very low cost of living. Small international community — expect close faculty relationships.", places: ["Yellowstone National Park", "Grand Teton National Park", "Jackson Hole", "Devils Tower", "Flaming Gorge"] },
};

export const FIPS_TO_ABBR: Record<string, string> = {
  "01": "AL", "04": "AZ", "05": "AR", "06": "CA", "08": "CO",
  "09": "CT", "10": "DE", "11": "DC", "12": "FL", "13": "GA",
  "16": "ID", "17": "IL", "18": "IN", "19": "IA", "20": "KS", "21": "KY",
  "22": "LA", "23": "ME", "24": "MD", "25": "MA", "26": "MI", "27": "MN",
  "28": "MS", "29": "MO", "30": "MT", "31": "NE", "32": "NV", "33": "NH",
  "34": "NJ", "35": "NM", "36": "NY", "37": "NC", "38": "ND", "39": "OH",
  "40": "OK", "41": "OR", "42": "PA", "44": "RI", "45": "SC", "46": "SD",
  "47": "TN", "48": "TX", "49": "UT", "50": "VT", "51": "VA", "53": "WA",
  "54": "WV", "55": "WI", "56": "WY",
};
