-- Restructure posting feature to support:
-- - user-owned posts
-- - multiple post images
-- - "helpful" reactions

-- Archive legacy table if it exists and new table has not been created yet.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'Post'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name = 'Posts'
  ) THEN
    ALTER TABLE public."Post" RENAME TO "PostLegacy";
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public."Posts" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES public."Users"(id) ON DELETE CASCADE,
  title TEXT NOT NULL CHECK (char_length(trim(title)) > 0),
  body TEXT NOT NULL CHECK (char_length(trim(body)) > 0),
  images TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "helpfulCount" INTEGER NOT NULL DEFAULT 0 CHECK ("helpfulCount" >= 0),
  "reviewStatus" TEXT NOT NULL DEFAULT 'approved' CHECK ("reviewStatus" IN ('pending', 'approved', 'rejected')),
  "reviewedAt" TIMESTAMPTZ NULL,
  "reviewedBy" INTEGER NULL REFERENCES public."Users"(id) ON DELETE SET NULL,
  "reviewNote" TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Backward compatibility: normalize column naming to camelCase if an older snake_case
-- (or lowercase unquoted) version of Posts already exists.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'user_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'userId'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN user_id TO "userId"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'userid'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'userId'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN userid TO "userId"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'created_at'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'createdAt'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN created_at TO "createdAt"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'updated_at'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'updatedAt'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN updated_at TO "updatedAt"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'helpful_count'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'helpfulCount'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN helpful_count TO "helpfulCount"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'review_status'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewStatus'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN review_status TO "reviewStatus"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewed_at'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewedAt'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN reviewed_at TO "reviewedAt"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewed_by'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewedBy'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN reviewed_by TO "reviewedBy"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'review_note'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'Posts' AND column_name = 'reviewNote'
  ) THEN
    EXECUTE 'ALTER TABLE public."Posts" RENAME COLUMN review_note TO "reviewNote"';
  END IF;
END $$;

ALTER TABLE public."Posts"
  ADD COLUMN IF NOT EXISTS "userId" INTEGER REFERENCES public."Users"(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS body TEXT,
  ADD COLUMN IF NOT EXISTS images TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "helpfulCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE public."Posts"
  ADD COLUMN IF NOT EXISTS "reviewStatus" TEXT NOT NULL DEFAULT 'approved' CHECK ("reviewStatus" IN ('pending', 'approved', 'rejected')),
  ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS "reviewedBy" INTEGER NULL REFERENCES public."Users"(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS "reviewNote" TEXT NULL;

CREATE TABLE IF NOT EXISTS public."PostHelpfuls" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postId" INTEGER NOT NULL REFERENCES public."Posts"(id) ON DELETE CASCADE,
  "userId" INTEGER NOT NULL REFERENCES public."Users"(id) ON DELETE CASCADE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE ("postId", "userId")
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'post_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'postId'
  ) THEN
    EXECUTE 'ALTER TABLE public."PostHelpfuls" RENAME COLUMN post_id TO "postId"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'user_id'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'userId'
  ) THEN
    EXECUTE 'ALTER TABLE public."PostHelpfuls" RENAME COLUMN user_id TO "userId"';
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'created_at'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'PostHelpfuls' AND column_name = 'createdAt'
  ) THEN
    EXECUTE 'ALTER TABLE public."PostHelpfuls" RENAME COLUMN created_at TO "createdAt"';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_posts_user_created_at ON public."Posts" ("userId", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON public."Posts" ("createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_posts_review_status_created_at ON public."Posts" ("reviewStatus", "createdAt" DESC);
CREATE INDEX IF NOT EXISTS idx_post_helpfuls_post_id ON public."PostHelpfuls" ("postId");
CREATE INDEX IF NOT EXISTS idx_post_helpfuls_user_id ON public."PostHelpfuls" ("userId");

ALTER TABLE public."Users"
  ADD COLUMN IF NOT EXISTS "appreciationTokens" INTEGER NOT NULL DEFAULT 0 CHECK ("appreciationTokens" >= 0);

CREATE TABLE IF NOT EXISTS public."ShopRedemptions" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" INTEGER NOT NULL REFERENCES public."Users"(id) ON DELETE CASCADE,
  "itemKey" TEXT NOT NULL,
  "itemLabel" TEXT NOT NULL,
  cost INTEGER NOT NULL CHECK (cost > 0),
  status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested', 'approved', 'fulfilled', 'rejected')),
  note TEXT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shop_redemptions_user_created_at ON public."ShopRedemptions" ("userId", "createdAt" DESC);

CREATE OR REPLACE FUNCTION public.set_posts_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW."updatedAt" = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_posts_updated_at ON public."Posts";
CREATE TRIGGER trg_posts_updated_at
BEFORE UPDATE ON public."Posts"
FOR EACH ROW
EXECUTE FUNCTION public.set_posts_updated_at();

ALTER TABLE public."Posts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PostHelpfuls" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ShopRedemptions" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'Posts' AND policyname = 'Posts allow app access'
  ) THEN
    CREATE POLICY "Posts allow app access"
      ON public."Posts"
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'PostHelpfuls' AND policyname = 'PostHelpfuls allow app access'
  ) THEN
    CREATE POLICY "PostHelpfuls allow app access"
      ON public."PostHelpfuls"
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'ShopRedemptions' AND policyname = 'ShopRedemptions allow app access'
  ) THEN
    CREATE POLICY "ShopRedemptions allow app access"
      ON public."ShopRedemptions"
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- Public storage bucket for post images (uploaded from the dashboard).
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'post-images',
  'post-images',
  true,
  6291456,
  ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Public read post-images'
  ) THEN
    CREATE POLICY "Public read post-images"
      ON storage.objects
      FOR SELECT
      USING (bucket_id = 'post-images');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'Public upload post-images'
  ) THEN
    CREATE POLICY "Public upload post-images"
      ON storage.objects
      FOR INSERT
      WITH CHECK (bucket_id = 'post-images');
  END IF;
END $$;
